import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { Products, UserInformation, AmazonState } from "./types";

// Retrieve user info from localStorage if available
const storedUserInfo = localStorage.getItem("userInformation");
const initialState: AmazonState = {
  products: [],
  userInformation: storedUserInfo ? JSON.parse(storedUserInfo) : null,
};

export const amazonSlice = createSlice({
  name: "amazon",
  initialState,
  reducers: {
    // Action to add a product to the cart
    addToCart: (state, action: PayloadAction<Products>) => {
      const item = state.products.find((item) => item.id === action.payload.id);
      if (item) {
        item.quantity += action.payload.quantity;
      } else {
        state.products.push(action.payload);
      }
    },
    // Action to remove a product from the cart
    deleteItem: (state, action: PayloadAction<number>) => {
      state.products = state.products.filter(
        (item) => item.id !== action.payload
      );
    },
    setUserInfo: (state, action: PayloadAction<UserInformation>) => {
      state.userInformation = action.payload;
      // Store user information in localStorage
      localStorage.setItem("userInformation", JSON.stringify(action.payload));
    },
    // Action to clear the cart
    clearCart: (state) => {
      state.products = [];
    },
    incrementItem: (state, action: PayloadAction<number>) => {
      const item = state.products.find((item) => item.id === action.payload);
      if (item) {
        item.quantity += 1;
      }
    },
    decrementItem: (state, action: PayloadAction<number>) => {
      const item = state.products.find((item) => item.id === action.payload);
      if (item && item.quantity > 1) {
        item.quantity -= 1;
      }
    },
    setSignOut: (state) => {
      state.userInformation = null;
      // Remove user information from localStorage
      localStorage.removeItem("userInformation");
    },
    setProducts: (state, action: PayloadAction<Products[]>) => {
      state.products = action.payload;
    },
  },
});

// Export the action creators generated by createSlice
export const {
  setProducts,
  setSignOut,
  addToCart,
  deleteItem,
  clearCart,
  decrementItem,
  incrementItem,
  setUserInfo,
} = amazonSlice.actions;

// Export the reducer function to be used in the store configuration
export default amazonSlice.reducer;
