const showAllList = [
    "All Departments",
    "Arts & Crafts",
    "Automotive",
    "Baby",
    "Beauty & Personal Care",
    "Books",
    "Boys Fashions",
    "Computers",
    "Deals",
    "Digital Music",
    "Electronics",
    "Health & HouseHold",
    "Gift Cards",
    "Grocery & Gourmet",
    "Health & Household",
    "Home & Kitchen",
    "Industrial & Scientific",
    "Kindle Store",
    "Luggage",
    "Mens Fashion",
    "Movies & TV",
    "Music, CDs & Vinyl",
    "Pet Supplies",
    "Prime Video",
    "Software",
    "Sports & Outdoors",
    "Tools & Home Improvement",
    "Toys & Games",
    "Video Games",
    "Womens Fashion",
  ];

  export default showAllList
